const ApiPath = {
	LOGIN: '/api/auth/login',
	REGISTER: 'api/auth/register',
	LOGOFF: '/api/auth/logoff',
	USER_UPDATE: '/api/user/update',
	USER_LIST: '/api/user/list',
	USER_WALLET_CREATE: '/api/user/balance/wallet/create',
	USER_WALLET_INFO: '/api/user/balance/wallet/info',
	USER_WALLET_RECHARGE: '/api/user/balance/wallet/recharge',
	REFRESH_TOKEN: '/api/auth/refresh_token',
	VERIFY: '/api/auth/verify',
	CARGO_ADD: '/api/cargo/add',
	CARGO_UPDATE: '/api/cargo/update',
	CARGO_INFO: '/api/cargo/info',
	CARGO_LIST_PUBLISHED: '/api/cargo/published/list',
	CARGO_LIST: '/api/cargo/list',
	CARGO_LIST_AUDIT: '/api/cargo/audit/list',
	CARGO_AUDIT: '/api/cargo/audit',
	AUCTION_ADD: '/api/auction/audit/add',
	AUCTION_UPDATE: '/api/auction/update',
	AUCTION_INFO: '/api/auction/info',
	AUCTION_LIST: '/api/auction/list',
	AUCTION_LIST_PUBLISHED: '/api/auction/published/list',
};
export { ApiPath };
