const ApiPath = {
	LOGIN: '/api/auth/login',
	REGISTER: 'api/auth/register',
	LOGOFF: '/api/auth/logoff',
	USER_UPDATE: '/api/user/update/info',
	USER_LIST: '/api/user/list',
	USER_WALLET_CREATE: '/api/user/balance/wallet/create',
	USER_WALLET_INFO: '/api/user/balance/wallet/info',
	USER_WALLET_RECHARGE: '/api/user/balance/wallet/recharge',
	REFRESH_TOKEN: '/api/auth/refresh_token',
	VERIFY: '/api/auth/verify',
	CARGO_ADD: '/api/cargo/add',
	CARGO_UPDATE: '/api/cargo/update',
	CARGO_INFO: '/api/cargo/info',
	CARGO_LIST_PUBLISHED: '/api/cargo/published/list',
	CARGO_LIST: '/api/cargo/list',
	CARGO_LIST_AUDIT: '/api/cargo/audit/list',
	CARGO_AUDIT: '/api/cargo/audit',
	CARGO_USER_LIST: '/api/cargo/user/list',
	AUCTION_ADD: '/api/auction/audit/add',
	AUCTION_UPDATE: '/api/auction/update',
	AUCTION_INFO: '/api/auction/info',
	AUCTION_INFO_BY_CARGOID: '/api/auction/info/cargo',
	AUCTION_LIST: '/api/auction/list',
	AUCTION_USER_LIST: '/api/auction/user/list',
	AUCTION_LIST_PUBLISHED: '/api/auction/published/list',
	AUCTION_OPERATION_INFO: '/api/auction/operation/info',
	AUCTION_OPERATION_ADD: '/api/auction/operation/add',
	AUCTION_LOG_INFO: '/api/auction/info/log',
	ORDER_INFO: '/api/order/info',
	ORDER_LIST: '/api/order/user/list',
	ORDER_CANCEL: '/api/order/user/cancel',
	ORDER_PAY: '/api/order/user/pay',
	FILE_UPLOAD: '/api/file/upload',
	FILE_UPLOAD_AVATAR: '/api/file/upload/avatar',
};
export { ApiPath };
